version: '3.8'

services:
  frontend:
    image: ghcr.io/t-history/frontend:main
    ports:
      - '3000:3000'
    depends_on: 
      - api

  api:
    image: ghcr.io/t-history/api:main
    ports:
      - '8080:8080'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MONGO_CONNECTION_STRING: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}"
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BACKUP_BUCKET: ${S3_BACKUP_BUCKET} 

    depends_on:
      - redis
      - mongodb
  
  loader:
    image: ghcr.io/t-history/tg-loader:main
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MONGO_CONNECTION_STRING: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}"
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ITERATION_FOR_CHAT: 1000
      API_ID: ${TG_API_ID}
      API_HASH: ${TG_API_HASH}
    depends_on:
      - redis
      - mongodb
  
  bull-board:
    image: bull-board
    ports:
      - "5050:3000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    command: ["redis-server"]
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}